system:
  db-type: mysql
  cache-type: redis
  port: '8888'
  env: 'product'  #  product Change to "develop" to skip authentication for development mode
push:
  push_iphone_token: "7GtdaA7z5cfZeZYhEgUUgg"
mysql:
  username: root
  password: '0807baobei123'
  path: 'localhost:3306'
  dbname: 'peekaboo'
  config: 'charset=utf8mb4&parseTime=true&loc=Local&timeout=1s'
  max-idle-conns: 10
  max-open-conns: 10
  log-mode: false

redis:
  addr: 'localhost:6379'
  password:
  db: 0

log:
  level: debug
  format: console
  prefix: '[peekaboo]'
  director: log
  link-name: latest_log
  showLine: true
  encode-level: LowercaseColorLevelEncoder
  stacktrace-key: stacktrace
  log-in-console: true

jwt:
  signing-key: 'peekaboo'
  expire: 7200

baidumap:
  ip_location_url: "http://api.map.baidu.com/location/ip?ak="
  ak: "bYytMmuePGyxI4Y4mYVhiV4TQfqvL4tF"